### ISSUE TITLE
BUG: Map preview fails when 'center' property is not present in metadata

### ISSUE THREAD

**Issue by ItalyPaleAle** [consbio/mbtileserver#137] opened 2022-02-17 16:11 UTC
I am not able to view the map. Every time I try (using Docker, installing with `go get`, or re-compiling from scratch) I get a blank page and this error in the browser's console:

```
Uncaught TypeError: tileJSON.center is undefined
    <anonymous> http://localhost:8080/services/mymap/map:112
```

Error is in both Edge (Chromium) and Firefox.

**Comment by brendan-ward** [comment] 2022-02-17 16:25
@ItalyPaleAle it sounds like the issue is that the `metadata` table for your tileset does not contain an entry for `center`, which is optional according to the [TileJSON spec](https://github.com/mapbox/tilejson-spec/tree/master/2.2.0) - but I must have always expected it to be present within the maps.  Most tools that create tiles produce a metadata entry for `center`.  Out of curiosity, how did you create your tileset?

As a quick fix, you can add an entry for `center` to your tileset(s) and restart the server.

Is this problem showing up for an image tileset or a vector tileset?

**Comment by ItalyPaleAle** [comment] 2022-02-17 16:33
Thanks for the quick response and for pinpointing the issue quickly!

I'm very new to working with TileJSON and maps. I was trying with a map I created with tilemaker from OSM data. It's a vector tileset.

Let me look into how to add a center property - I'm really brand new to this :)

**Comment by ItalyPaleAle** [comment] 2022-02-17 16:41
I submitted a PR that fixes the issue!

**Comment by brendan-ward** [comment] 2022-02-17 16:42
You can open the tileset using a SQLite viewer like [DB Browser for SQLite](https://sqlitebrowser.org/), then navigate to the metadata table, add an entry for `center` (longitude, latitude, zoom), then save it.  Zoom is arbitrary; I often use the lowest zoom of a tileset.

**Comment by ItalyPaleAle** [comment] 2022-02-17 16:51
Thank you!

**Comment by brendan-ward** [comment] 2022-02-17 16:51
See also [tilemaker #380](https://github.com/systemed/tilemaker/issues/380); looks like this is now fixed in tilemaker `master` branch

**Closed** 2022-02-17 16:53 UTC
Labels: bug
