### ISSUE TITLE
Map preview error

### ISSUE THREAD

**Issue by sikmir** [consbio/mbtileserver#81] opened 2019-11-14 23:21 UTC
### Steps to reproduce
```sh
$ # mb-util ➠ https://github.com/mapbox/mbutil
$ mb-util ~/png-tiles ./mbtiles/testdata/test.mbtiles
$ docker-compose up -d
$ curl http://127.0.0.1:8080/services/test | jq
{
  "format": "png",
  "id": "test",
  "map": "http://127.0.0.1:8080/services/test/map",
  "maxzoom": 18,
  "minzoom": 0,
  "scheme": "xyz",
  "tilejson": "2.1.0",
  "tiles": [
    "http://127.0.0.1:8080/services/test/tiles/{z}/{x}/{y}.png"
  ]
}
$ curl http://127.0.0.1:8080/services/test/map
Internal Server Error
$ docker-compose logs mbtileserver
...
mbtileserver     | time="2019-11-14T22:57:50Z" level=error msg="could not parse template asset \"map\": html/template: cannot Parse after Execute"
mbtileserver     | time="2019-11-14T22:57:52Z" level=error msg="template: \"map\" is an incomplete or empty template"
mbtileserver     | time="2019-11-14T22:57:53Z" level=error msg="template: \"map\" is an incomplete or empty template"
```

**Comment by brendan-ward** [comment] 2019-11-14 23:26
@sikmir thanks for reporting this.  I need a bit more information to go on, as this looks like a template / compilation issue rather than related to your data specifically.

What version of Go are you using?

Did you compile `mbtileserver` yourself or did you install via `go get`?

**Comment by sikmir** [comment] 2019-11-14 23:28
> What version of Go are you using?
> 
> Did you compile mbtileserver yourself or did you install via go get?

I use Docker container:
https://github.com/consbio/mbtileserver/blob/10eb6193b711e9b007edb060721b61737de550a5/docker-compose.yml#L5

**Comment by brendan-ward** [comment] 2019-11-15 03:23
@sikmir I am not able to reproduce with `consbio/mbtilserver:latest` or by executing outside docker.

Your errors indicate an error while processing the template file for `templates/map.html`.  This file is included within a virtual file system in the executable in your docker container, and so it shouldn't change based on your environment or your specific data.  I'm not seeing anything obvious that would cause the template to fail to parse based on data; we are only passing in the ID of the service (`test` in this case).

A few questions, since I can't reproduce yet:
1. are you able to access tiles from this service directly?
2. if you use one of our valid test files (https://github.com/consbio/mbtileserver/blob/master/mbtiles/testdata/geography-class-png.mbtiles) - does the same error occur for you?
3. are you able to access any of the static assets, e.g., `http://127.0.0.1:8080/static/core.min.js`?

**Comment by sikmir** [comment] 2019-11-15 08:55
Well, just to be sure, let's doublecheck from inside the container and using _geography-class-png.mbtiles_:
```sh
$ docker inspect --format='{{index .RepoDigests 0}}' consbio/mbtileserver:latest
consbio/mbtileserver@sha256:c9801e79a79ba78dfce78a401c502715efc775d54e9262076e1e2478663d71d9
$ docker exec -it mbtileserver sh
/ # wget -qSO - http://127.0.0.1:8000/services/geography-class-png > /dev/null
  HTTP/1.1 200 OK
  ...
/ # wget -qSO - http://127.0.0.1:8000/services/geography-class-png/map > /dev/null
  HTTP/1.1 200 OK
  ...
/ # wget -qSO - http://127.0.0.1:8000/static/core.min.js > /dev/null
  HTTP/1.1 200 OK
  ...
```
It seems OK now and my original _test.mbtiles_ map preview doesn't lead to internal error. But... bad news is that I've restarted my docker container before that, so I can't reproduce the original problem as well now. That means a potential problem still exists, but not reproducable (so far).

> 1. are you able to access tiles from this service directly?

Yes, when the error was reproducable (before restart), I definitely was able to access tiles.

Well, here is another unrelated problem:
```sh
$ curl -s http://127.0.0.1:8080/services/geography-class-png | jq '.bounds'
[
  -180,
  -85.0511,
  180,
  85.0511
]
$ # mb-util doesn't generate bounds
$ curl -s http://127.0.0.1:8080/services/test | jq '.bounds'
null
```
Trying to open http://127.0.0.1:8080/services/test/map in browser:
```
Paused on exception
TypeError: b is undefined
```
Caused by:
https://github.com/consbio/mbtileserver/blob/10eb6193b711e9b007edb060721b61737de550a5/handlers/templates/map.html#L86-L90

**Comment by brendan-ward** [comment] 2019-11-15 16:51
@sikmir thank you for following up on this further.  I agree that the clear presence of the issue the first time and the lack of reproducibility on the second is concerning, since the functionality to render the template is not stateful (and thus should be exactly the same _every_ time the docker container is run).

I opened #83 for the `bounds` issue.

Since this error is not yet reproducible, I'm going to close this issue - but please feel free to reopen if you see it again and can help with a reproducible test case.

**Closed by brendan-ward** 2019-11-15 16:51 UTC
