### ISSUE TITLE
Too large memory usage in last version

### ISSUE THREAD

**Issue by asmyasnikov** [consbio/mbtileserver#103] opened 2020-05-20 15:42 UTC
Hi!
I'm use cgroups memory limitations from docker-compose.yml
```
  mbtiles:
    image: mbtiles
    environment:
      - TILE_DIR=/external,/internal
      - PORT=80
    networks:
      phoenix:
        ipv4_address: 172.18.0.21
    read_only: True
    restart: always
    volumes: ['/opt/mbtiles/:/internal', '/opt/usb/mbtiles/:/external']
    logging:
      driver: "none"
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 30M
```
Limit 30M not exceed in older version. But last version (https://github.com/consbio/mbtileserver/commit/ca4a94e0c5a4487c64d271e6d1428a6aefcd094c) want about 1G of memory without limitation  =(
This is a critical for single-board computers...
Log:
```
mbtiles_1               | time="2020-05-20T15:45:59Z" level=info msg="Searching for tilesets in /external\n"
mbtiles_1               | time="2020-05-20T15:45:59Z" level=info msg="Searching for tilesets in /internal\n"
mbtiles_1               | time="2020-05-20T15:46:01Z" level=info msg="Searching for tilesets in /external\n"
mbtiles_1               | time="2020-05-20T15:46:01Z" level=info msg="Searching for tilesets in /internal\n"
docker_mbtiles_1 exited with code 137
mbtiles_1               | time="2020-05-20T15:46:04Z" level=info msg="Searching for tilesets in /external\n"
mbtiles_1               | time="2020-05-20T15:46:04Z" level=info msg="Searching for tilesets in /internal\n"
```
internal and external paths contains big mbtiles files:
```
root@debian:/etc/docker# du -sh /opt/mbtiles/*
9,2M    /opt/mbtiles/countries-raster.mbtiles
18G     /opt/mbtiles/world_yandex.mbtiles
root@debian:/etc/docker# du -sh /opt/usb/mbtiles/*
52G     /opt/usb/mbtiles/osm-2017-07-03-v3.6.1-planet.mbtiles
```

**Comment by brendan-ward** [comment] 2020-05-20 15:50
@asmyasnikov thanks for reporting this.  I haven't seen that to be the case in my own usage so far.

Can you help me understand some of the factors involved here?

Are you building your own Docker container for mbtileserver?  If so, which version of Go?

Does it run out of memory immediately while searching for tiles, or does the server run for a while before running out of memory?

How many tiles are in internal vs external folders?

**Comment by asmyasnikov** [comment] 2020-05-20 16:04
> internal and external paths contains big mbtiles files:
> ```
> root@debian:/etc/docker# du -sh /opt/mbtiles/*
> 9,2M    /opt/mbtiles/countries-raster.mbtiles
> 18G     /opt/mbtiles/world_yandex.mbtiles
> root@debian:/etc/docker# du -sh /opt/usb/mbtiles/*
> 52G     /opt/usb/mbtiles/osm-2017-07-03-v3.6.1-planet.mbtiles
> ```

**Comment by asmyasnikov** [comment] 2020-05-20 16:09
> Are you building your own Docker container for mbtileserver? If so, which version of Go?
I'm build mbtileserver with go1.14
And yes, I'm running mbtileserver inside a docker container
My Dockerfile:
```
ARG ARCH=arm32v7
ARG QARCH=arm
ARG GOARCH=arm
ARG ORIGIN=github.com/consbio/mbtileserver
FROM ${ARCH}/busybox:glibc AS base
ARG QARCH=arm
ARG GOARCH=arm
ARG ORIGIN=None
FROM multiarch/qemu-user-static:x86_64-${QARCH} as qemu
ARG ARCH=arm32v7
ARG GOARCH=arm
ARG ORIGIN=None
FROM --platform=linux/${GOARCH} ${ARCH}/golang:latest AS build
COPY --from=qemu /usr/bin/ /usr/bin/
ARG ORIGIN=None
WORKDIR /build
RUN git clone https://${ORIGIN}.git .
RUN go build -mod=vendor -ldflags="-w -s" -o ./mbtileserver
RUN cp $(ldd ./mbtileserver | grep libdl.so | awk '{print $3}') /build/libdl.so.2
FROM base
ARG VERSION=None
ENV VERSION=$VERSION
COPY --from=build /build/libdl.so.2 /lib/libdl.so.2
COPY --from=build /build/mbtileserver /mbtileserver
ENTRYPOINT ["/mbtileserver"]
CMD []
```

**Comment by asmyasnikov** [comment] 2020-05-20 16:12
> Does it run out of memory immediately while searching for tiles, or does the server run for a while before running out of memory?

No. A familiar message "Use Ctrl-C to exit the server" is missing

**Comment by asmyasnikov** [comment] 2020-05-20 16:16
Without limitaion of memory I have
```
mbtiles_1               | time="2020-05-20T16:13:10Z" level=info msg="Searching for tilesets in /external\n"
mbtiles_1               | time="2020-05-20T16:13:10Z" level=info msg="Searching for tilesets in /internal\n"
mbtiles_1               |
mbtiles_1               | --------------------------------------
mbtiles_1               | Use Ctrl-C to exit the server
mbtiles_1               | --------------------------------------
mbtiles_1               | HTTP server started on port 80
mbtiles_1               | time="2020-05-20T16:13:28Z" level=info msg="Published 3 services"
```
And after that usage of memory from 100% decresed to normal.

**Comment by asmyasnikov** [comment] 2020-05-20 16:23
![Снимок экрана от 2020-05-20 19-21-36](https://user-images.githubusercontent.com/14202262/82471398-4f71fe80-9acf-11ea-976e-76aa155a010f.png)
Start of process

**Comment by brendan-ward** [comment] 2020-05-20 16:23
Thanks for the additional info.  We are allocating a number of objects at startup, but most of those are proportional to the number of tilesets rather than their size.

I don't have very large tilesets available for testing with at the moment, but could rig up a test setup where memory is similarly limited during startup.  I can't promise I can get to this immediately.

You might also be able to do some minimal testing here that could help:
1. try a test where you start the server but point it to an empty directory.  If this fails, this tells us we're grabbing a lot of memory during startup that isn't related to tiles.
2. try a test where you start the server only pointing at your internal directory.
3. try another test where you start the server only pointing at your external directory.  If this fails but 2 does not, then please try an additional test where you have the 56GB tileset on an internal directory instead.

**Comment by asmyasnikov** [comment] 2020-05-20 16:34
> try a test where you start the server but point it to an empty directory. If this fails, this tells us we're grabbing a lot of memory during startup that isn't related to tiles.

No too memory usage

**Comment by asmyasnikov** [comment] 2020-05-20 16:36
> try a test where you start the server only pointing at your internal directory.

![Снимок экрана от 2020-05-20 19-36-16](https://user-images.githubusercontent.com/14202262/82472687-3ec28800-9ad1-11ea-917b-ac1699e80071.png)

**Comment by brendan-ward** [comment] 2020-05-20 16:37
Sorry, I couldn't understand what you meant by:
> No too memory usage

Do you mean it started correctly?

**Comment by asmyasnikov** [comment] 2020-05-20 16:41
> try another test where you start the server only pointing at your external directory. 

No memory excess. Yes, start correctly

**Comment by asmyasnikov** [comment] 2020-05-20 16:57
But I cannot view map from `/opt/usb/mbtiles/osm-2017-07-03-v3.6.1-planet.mbtiles` (pbf vector tiles). This tileset present in /services response
Too memory usage tileset `/opt/mbtiles/world_yandex.mbtiles` (from internal) viewed on my map (mbtileserver returning tiles by z/x/y requests). Tileset `/opt/mbtiles/countries-raster.mbtiles` (from internal) also viewed on my map. 
Shaize!
I find out the features...

**Comment by asmyasnikov** [comment] 2020-05-20 17:00
On active moving of map (intensive requests z/x/y) mbtileserver also too memory usage 
![Снимок экрана от 2020-05-20 20-00-26](https://user-images.githubusercontent.com/14202262/82475055-931b3700-9ad4-11ea-8ca8-cba398432b3a.png)

**Comment by brendan-ward** [comment] 2020-05-20 17:06
I usually see`broken pipe` messages when the client (browser map library) has canceled the tile requests; usually when aggressively panning / zooming in the web map.

Are you able to test with the prior commit (f2305b518fa81a9d7a3695abc0e4131401a936e6) just against your internal directory?  It would be interesting to know if the refactor introduced a major memory regression.

**Comment by asmyasnikov** [comment] 2020-05-20 17:29
> Are you able to test with the prior commit (f2305b5) just against your internal directory? It would be interesting to know if the refactor introduced a major memory regression.
Also too memory usage in f2305b5. 
![Снимок экрана от 2020-05-20 20-00-26](https://user-images.githubusercontent.com/14202262/82477643-6bc66900-9ad8-11ea-9855-ea9635491bfc.png)

**Comment by asmyasnikov** [comment] 2020-05-20 17:32
I m understand nothing now
I will search my stable (by memory usage version) tomorrow.

**Comment by brendan-ward** [comment] 2020-05-20 18:00
Thanks @asmyasnikov for running these tests!

It looks like the memory on startup is stable between the prior and latest commits, so we didn't introduce a memory regression as far as I can tell.  That's good news, at least.

I wonder if Go is not respecting the cgroups memory policy?  Are you indeed seeing OOM errors in the log, as described here: https://fabianlee.org/2020/01/18/docker-placing-limits-on-container-memory-using-cgroups/

It could also be another issue:
* https://github.com/golang/go/issues/37525
* how `GOGC` interacts with available memory, see https://golang.org/pkg/runtime/

**Comment by asmyasnikov** [comment] 2020-05-20 19:07
I found small interpretation about not viewing map from vector (pbf) mbtiles file 
```
root@debian:/du -s # used file
53492336        /opt/usb/mbtiles/osm-2017-07-03-v3.6.1-planet.mbtiles
root@debian:/du -s # original file
53492348        /opt/usb2/mbtiles/osm-2017-07-03-v3.6.1-planet.mbtiles
```
File was corrupted. Maybe because a storage is a USB-device
I wil try to restore file and retry running mbtileserver

**Comment by asmyasnikov** [comment] 2020-05-20 19:47
<img width="722" alt="image" src="https://user-images.githubusercontent.com/14202262/82490093-67577b80-9aeb-11ea-92f9-dcc8c09d300a.png">
This is latest stable version (https://github.com/consbio/mbtileserver/commit/8c21f5ac4c1a6fa3e3a0d6115f86881fba359ddc) of mbtileserver which I was used long time. I re-build (few minute ago) this version with my Dockerfile (latest golang and other). docker-compose are not modified.

**Comment by asmyasnikov** [comment] 2020-05-20 19:52
> I wonder if Go is not respecting the cgroups memory policy? Are you indeed seeing OOM errors in the log, as described here: https://fabianlee.org/2020/01/18/docker-placing-limits-on-container-memory-using-cgroups/

```
root@debian:/etc/docker# dmesg | grep -Ei "killed process"
[  531.528371] Killed process 7577 (mbtileserver) total-vm:1169360kB, anon-rss:13744kB, file-rss:0kB, shmem-rss:0kB
[  593.809625] Killed process 8035 (mbtileserver) total-vm:1169104kB, anon-rss:15044kB, file-rss:0kB, shmem-rss:0kB
[  656.035194] Killed process 8506 (mbtileserver) total-vm:1167952kB, anon-rss:11648kB, file-rss:0kB, shmem-rss:0kB
[  718.287512] Killed process 8960 (mbtileserver) total-vm:1168652kB, anon-rss:15032kB, file-rss:0kB, shmem-rss:0kB
[  780.535074] Killed process 9438 (mbtileserver) total-vm:1242836kB, anon-rss:13756kB, file-rss:0kB, shmem-rss:0kB
[ 1058.944100] Killed process 11774 (mbtileserver) total-vm:1168640kB, anon-rss:15004kB, file-rss:4kB, shmem-rss:13780kB
[ 1061.036764] Killed process 11892 (mbtileserver) total-vm:1242600kB, anon-rss:17232kB, file-rss:4kB, shmem-rss:16652kB
[ 1063.157830] Killed process 12010 (mbtileserver) total-vm:1167460kB, anon-rss:13328kB, file-rss:4kB, shmem-rss:16372kB
[ 1065.414487] Killed process 12129 (mbtileserver) total-vm:1168612kB, anon-rss:17240kB, file-rss:4kB, shmem-rss:16468kB
[ 1068.108419] Killed process 12246 (mbtileserver) total-vm:1242600kB, anon-rss:13160kB, file-rss:4kB, shmem-rss:16564kB
[ 1071.586636] Killed process 12372 (mbtileserver) total-vm:1242856kB, anon-rss:15192kB, file-rss:4kB, shmem-rss:16364kB
[ 1076.798350] Killed process 12506 (mbtileserver) total-vm:1316588kB, anon-rss:15220kB, file-rss:4kB, shmem-rss:16436kB
[ 1085.463741] Killed process 12657 (mbtileserver) total-vm:1242600kB, anon-rss:15160kB, file-rss:4kB, shmem-rss:16464kB
```

**Comment by brendan-ward** [comment] 2020-05-20 20:02
Interesting!  And confusing!

There really aren't substantive differences between that commit and the previous one you tested above.  It seems that f2305b518fa81a9d7a3695abc0e4131401a936e6 should have had the same memory profile as that branch, because it was before the substantive changes were merged in.

Would you mind trying with the common ancestor (a613fe59f49b841006c5f1ad2fa23e4444e7090b) between that branch and master?

**Comment by asmyasnikov** [comment] 2020-05-20 20:13
> Would you mind trying with the common ancestor (a613fe5) between that branch and master?

It is a stable version (by memory and CPU on start and moving map)

**Comment by asmyasnikov** [comment] 2020-05-20 20:20
ca4a94e also ok

**Comment by asmyasnikov** [comment] 2020-05-20 20:24
<img width="722" alt="image" src="https://user-images.githubusercontent.com/14202262/82493687-08950080-9af1-11ea-8d6d-20c2a89ba762.png">
 446c5e4 some peaks on moving map

**Comment by asmyasnikov** [comment] 2020-05-20 20:26
Mistics...

**Comment by brendan-ward** [comment] 2020-05-20 20:27
ca4a94e0c5a4487c64d271e6d1428a6aefcd094c is the tip of master.  Is that correct?  This is the one that started all the issues at the top of the thread.

**Comment by asmyasnikov** [comment] 2020-05-20 20:29
<img width="722" alt="image" src="https://user-images.githubusercontent.com/14202262/82494030-9e309000-9af1-11ea-9f69-0fbe622c6f9b.png">
ca4a94e was look like this

**Comment by asmyasnikov** [comment] 2020-05-20 20:34
f2305b5 also rebuild, testing and getting this
<img width="722" alt="image" src="https://user-images.githubusercontent.com/14202262/82494514-62e29100-9af2-11ea-8c3a-6cc2d54518b1.png">
I have no idea whats changed

**Comment by asmyasnikov** [comment] 2020-05-20 20:37
3 hours ago I was see too large of memory usage. Only mbtileserver (from 24 containers) using so large memory.
Sorry. I will be search another causes...

**Comment by asmyasnikov** [comment] 2020-05-20 20:39
O! I remembered. All of last tests I make with read-only volume `/internal:ro`. 
Now I will try to tests without `ro` flag

**Comment by asmyasnikov** [comment] 2020-05-20 20:42
<img width="722" alt="image" src="https://user-images.githubusercontent.com/14202262/82495178-63c7f280-9af3-11ea-8ee9-d638799dd143.png">
f2305b5 is looks wrong

**Comment by asmyasnikov** [comment] 2020-05-20 20:48
<img width="722" alt="image" src="https://user-images.githubusercontent.com/14202262/82495499-da64f000-9af3-11ea-9fe6-7a2f49c38562.png">
It is my stable version ( 8c21f5a )
Sorry. This bug only partly about of mbtileserver. Most causes about docker mounting ro/rw volumes.
Sorry yet.

**Comment by asmyasnikov** [comment] 2020-05-20 20:53
For your calm - see latest (head) stats
<img width="722" alt="image" src="https://user-images.githubusercontent.com/14202262/82496146-eb623100-9af4-11ea-86b7-f10c20137451.png">
Sorry
<img width="265" alt="image" src="https://user-images.githubusercontent.com/14202262/82496254-1d739300-9af5-11ea-90f8-9063d308a6b4.png">

**Closed** 2020-05-20 20:53 UTC

**Comment by brendan-ward** [comment] 2020-05-20 20:58
Thanks for your detailed investigation @asmyasnikov !  I appreciate all the effort you invested in this and in reporting back on it here.

I'm glad that our recent changes didn't introduce a memory regression, and that in general our memory profile is very low.

**Comment by asmyasnikov** [comment] 2020-05-20 21:05
<img width="265" alt="image" src="https://user-images.githubusercontent.com/14202262/82497381-cf5f8f00-9af6-11ea-8c58-1b89c8ae69f0.png">
=)))
